"""Preset text-prompt lists used by evaluation configs.

Each entry is a class. A string may contain comma-separated synonyms that
are sent to SAM 3 as separate queries and then max-pooled back to one class.
Users can pass any custom list instead of these presets.
"""

ADE20K = [
    "wall",
    "building",
    "sky",
    "floor",
    "tree",
    "ceiling",
    "road",
    "bed",
    "windowpane",
    "grass",
    "cabinet",
    "sidewalk",
    "person",
    "earth",
    "door",
    "table",
    "mountain",
    "plant",
    "curtain",
    "chair",
    "car",
    "water",
    "painting",
    "sofa",
    "shelf",
    "house",
    "sea",
    "mirror",
    "rug",
    "field",
    "armchair",
    "seat",
    "fence",
    "desk",
    "rock",
    "wardrobe",
    "lamp",
    "bathtub",
    "railing",
    "cushion",
    "base",
    "box",
    "column",
    "signboard",
    "chestofdrawers",
    "counter",
    "sand",
    "sink",
    "skyscraper",
    "fireplace",
    "refrigerator",
    "grandstand",
    "path",
    "stairs",
    "runway",
    "case",
    "pooltable",
    "pillow",
    "screendoor",
    "stairway",
    "river",
    "bridge",
    "bookcase",
    "blind",
    "coffeetable",
    "toilet",
    "flower",
    "book",
    "hill",
    "bench",
    "countertop",
    "stove",
    "palm",
    "kitchenisland",
    "computer",
    "swivelchair",
    "boat",
    "bar",
    "arcademachine",
    "hovel",
    "bus",
    "towel",
    "light",
    "truck",
    "tower",
    "chandelier",
    "awning",
    "streetlight",
    "booth",
    "televisionreceiver",
    "airplane",
    "dirttrack",
    "apparel",
    "pole",
    "land",
    "bannister",
    "escalator",
    "ottoman",
    "bottle",
    "buffet",
    "poster",
    "stage",
    "van",
    "ship",
    "fountain",
    "conveyerbelt",
    "canopy",
    "washer",
    "plaything",
    "swimmingpool",
    "stool",
    "barrel",
    "basket",
    "waterfall",
    "tent",
    "bag",
    "minibike",
    "cradle",
    "oven",
    "ball",
    "food",
    "step",
    "tank",
    "tradename",
    "microwave",
    "pot",
    "animal",
    "bicycle",
    "lake",
    "dishwasher",
    "screen",
    "blanket",
    "sculpture",
    "hood",
    "sconce",
    "vase",
    "trafficlight",
    "tray",
    "ashcan",
    "fan",
    "pier",
    "crtscreen",
    "plate",
    "monitor",
    "bulletinboard",
    "shower",
    "radiator",
    "glass",
    "clock",
    "flag",
]

BUILDING = [
    "background",
    "house",
]

CHN6_CUG = [
    "background",
    "road",
]

CITYSCAPES = [
    "road",
    "sidewalk",
    "building",
    "wall",
    "fence",
    "pole",
    "trafficlight",
    "trafficsign",
    ["tree", "hedge"],
    ["grass", "horizontal vegetation", "soil", "sand"],
    "sky",
    "person",
    "rider",
    "car",
    "truck",
    "bus",
    "train",
    "motorcycle",
    "bicycle",
]

COCO_OBJECT = [
    "background",
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
]

COCO_STUFF = [
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "trafficlight",
    "firehydrant",
    "stopsign",
    "parkingmeter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sportsball",
    "kite",
    "baseballbat",
    "baseballglove",
    "skateboard",
    "surfboard",
    "tennisracket",
    "bottle",
    "wineglass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hotdog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "pottedplant",
    "bed",
    "diningtable",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cellphone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddybear",
    "hairdrier",
    "toothbrush",
    "banner",
    "blanket",
    "branch",
    "bridge",
    "building-other",
    "bush",
    "cabinet",
    "cage",
    "cardboard",
    "carpet",
    "ceiling-other",
    "ceiling-tile",
    "cloth",
    "clothes",
    "clouds",
    "counter",
    "cupboard",
    "curtain",
    "desk-stuff",
    "dirt",
    "door-stuff",
    "fence",
    "floor-marble",
    "floor-other",
    "floor-stone",
    "floor-tile",
    "floor-wood",
    "flower",
    "fog",
    "food-other",
    "fruit",
    "furniture-other",
    "grass",
    "gravel",
    "ground-other",
    "hill",
    "house",
    "leaves",
    "light",
    "mat",
    "metal",
    "mirror-stuff",
    "moss",
    "mountain",
    "mud",
    "napkin",
    "net",
    "paper",
    "pavement",
    "pillow",
    "plant-other",
    "plastic",
    "platform",
    "playingfield",
    "railing",
    "railroad",
    "river",
    "road",
    "rock",
    "roof",
    "rug",
    "salad",
    "sand",
    "sea",
    "shelf",
    "sky-other",
    "skyscraper",
    "snow",
    "solid-other",
    "stairs",
    "stone",
    "straw",
    "structural-other",
    "table",
    "tent",
    "textile-other",
    "towel",
    "tree",
    "vegetable",
    "wall-brick",
    "wall-concrete",
    "wall-other",
    "wall-panel",
    "wall-stone",
    "wall-tile",
    "wall-wood",
    "water-other",
    "waterdrops",
    "window-blind",
    "window-other",
    "wood",
]

CONTEXT59 = [
    "aeroplane",
    "bag",
    "bed",
    "bedclothes",
    "bench",
    "bicycle",
    "bird",
    "boat",
    "book",
    "bottle",
    "building",
    "bus",
    "cabinet",
    "car",
    "cat",
    "ceiling",
    "chair",
    "cloth",
    "computer",
    "cow",
    "cup",
    "curtain",
    "dog",
    "door",
    "fence",
    "floor",
    "flower",
    "food",
    "grass",
    "ground",
    "horse",
    "keyboard",
    "light",
    "motorbike",
    "mountain",
    "mouse",
    "person",
    "plate",
    "platform",
    "pottedplant",
    "road",
    "rock",
    "sheep",
    "shelves",
    "sidewalk",
    "sign",
    "sky",
    "snow",
    "sofa",
    "table",
    "track",
    "train",
    "tree",
    "truck",
    "tvmonitor",
    "wall",
    "water",
    "window",
    "wood",
]

CONTEXT60 = [
    "background",
    "aeroplane",
    "bag",
    "bed",
    "bedclothes",
    "bench",
    "bicycle",
    "bird",
    "boat",
    "book",
    "bottle",
    "building",
    "bus",
    "cabinet",
    "car",
    "cat",
    "ceiling",
    "chair",
    "cloth",
    "computer",
    "cow",
    "cup",
    "curtain",
    "dog",
    "door",
    "fence",
    "floor",
    "flower",
    "food",
    "grass",
    "ground",
    "horse",
    "keyboard",
    "light",
    "motorbike",
    "mountain",
    "mouse",
    "person",
    "plate",
    "platform",
    "pottedplant",
    "road",
    "rock",
    "sheep",
    "shelves",
    "sidewalk",
    "sign",
    "sky",
    "snow",
    "sofa",
    "table",
    "track",
    "train",
    "tree",
    "truck",
    "tvmonitor",
    "wall",
    "water",
    "window",
    "wood",
]

ISAID = [
    "background",
    "ship",
    "store tank",
    "baseball diamond",
    "tennis court",
    "basketball court",
    "ground track field",
    "bridge",
    "large vehicle",
    "small vehicle",
    "helicopter",
    "swimming pool",
    "roundabout",
    "soccer ball field",
    "plane",
    "harbor",
]

INRIA = [
    "background",
    "building",
]

LEVIR_CD = [
    "background",
    "building",
]

LOVEDA = [
    "background",
    ["building", "house"],
    "road",
    "water",
    ["barren", "bareland", "soil"],
    ["forest", "tree"],
    "agricultural",
]

OPENEARTHMAP = [
    "background",
    ["bareland", "barren"],
    "grass",
    "pavement",
    "road",
    ["tree", "forest"],
    ["water", "river"],
    "cropland",
    ["building", "roof", "house"],
]

POTSDAM = [
    "road",
    "building",
    "grass",
    "tree",
    "car",
    "clutter",
]

ROAD = [
    "background",
    "road",
]

S2LOOKING = [
    "background",
    "building",
]

UAVID = [
    "background",
    "building",
    "road",
    "car",
    "tree",
    "vegetation",
    "human",
]

UDD5 = [
    "vegetation",
    "building",
    "road",
    "vehicle",
    "background",
]

VAIHINGEN = [
    "road",
    "building",
    "grass",
    "tree",
    "car",
    "clutter",
]

VDD = [
    "background",
    "facade",
    "road",
    "vegetation",
    "vehicle",
    "roof",
    "water",
]

VOC20 = [
    "aeroplane",
    "bicycle",
    "bird",
    ["boat", "ship"],
    "bottle",
    "bus",
    "car",
    "cat",
    "chair",
    "cow",
    ["table", "diningtable"],
    "dog",
    "horse",
    "motorbike",
    "person",
    "pottedplant",
    "sheep",
    "sofa",
    "train",
    ["television monitor", "tv monitor", "monitor", "television", "screen"],
]

VOC21 = [
    "background",
    "aeroplane",
    "bicycle",
    "bird",
    "ship",
    "bottle",
    "bus",
    "car",
    "cat",
    "chair",
    "cow",
    "table",
    "dog",
    "horse",
    "motorbike",
    "person",
    "pottedplant",
    "sheep",
    "sofa",
    "train",
    "tvmonitor",
]

WBS_SI = [
    "background",
    "water",
]

WHU = [
    "background",
    "building",
]

WHU_CD = [
    "background",
    "building",
]

XBD = [
    "background",
    "building",
]

GID = [
    "unlabeled",
    "built-up",
    "farmland",
    "forest",
    "meadow",
    "water",
]

GF_ROAD = [
    "background",
    "road",
]

GF7_BUILDING = [
    "background",
    "building",
]

STPLS3D = [
    ["ground", "road", "grass", "dirt", "water"],
    ["tree", "vegetation"],
    ["car", "truck"],
    "light pole",
    "fence",
    ["building", "clutter"],
]

DATASET_PROMPTS = {
    "loveda": LOVEDA,
    "openearthmap": OPENEARTHMAP,
    "potsdam": POTSDAM,
    "vaihingen": VAIHINGEN,
    "udd5": UDD5,
    "vdd": VDD,
    "uavid": UAVID,
    "whu": WHU,
    "whu_cd": WHU_CD,
    "inria": INRIA,
    "xbd": XBD,
    "levir_cd": LEVIR_CD,
    "s2looking": S2LOOKING,
    "isaid": ISAID,
    "chn6_cug": CHN6_CUG,
    "road": ROAD,
    "wbs_si": WBS_SI,
    "building": BUILDING,
    "voc20": VOC20,
    "voc21": VOC21,
    "cityscapes": CITYSCAPES,
    "context59": CONTEXT59,
    "context60": CONTEXT60,
    "ade20k": ADE20K,
    "coco_object": COCO_OBJECT,
    "coco_stuff": COCO_STUFF,
    "gid": GID,
    "gf_road": GF_ROAD,
    "gf7_building": GF7_BUILDING,
    "stpls3d": STPLS3D,
}
